trigger:
- master

pool:
  name: 'docker-pool'
  #vmImage: ubuntu-latest

variables:
- name: org_id
  value: "752089912425"
- name: billing_account
  value: "013B19-B6B12E-6CC016"
- name: group_billing_admins 
  value: "group_billing_admins@gcp-lz-endava.com"
- name: group_org_admins
  value: "group_org_admins@gcp-lz-endava.com"
- name: default_region
  value:  "europe-west2"
- name: parent_folder
  value: "798333110955"
- name: folder_prefix
  value: "med"
- name: project_prefix 
  value: "ned"
- name: domains_to_allow 
  value: "gcp-lz-endava.com"
- name: essential_contacts_domains_to_allow 
  value: "gcp-lz-endava.com"
- name: billing_data_users 
  value: "group_org_admins@gcp-lz-endava.com"  
- name: audit_data_users
  value: "gcp-security-admins@gcp-lz-endava.com"
- name: scc_notification_name
  value: "907480293660"
- name: enable_hub_and_spoke 
  value: 'true'
- name: create_access_context_manager_access_policy
  value: 'false'
- name: create_unique_tag_key 
  value: 'true' 
               
steps:
- task: DownloadSecureFile@1
  name: azure
  inputs:
    secureFile: 'azuredevops-orgadmin-1d8fd63dcdc4.json'

   